# Eksik Veri

### Amaç:

1. Eksik veri tespiti ve düzeltme

2. Güncel veriyi kaydet

---

### Adımlar:

1. veri setini yüklemek

2. eksik veri tespiti

3. eksik veri oran hesaplama

4. eksik veri inceleme

5. eksik veri silme

6. ortalama ile doldurma

7. medyan ile doldurma

8. mod ile doldurma

9. kategorik verileri mod doldurma

10. kategorik verileri sabit değer ile doldurma

11. güncel veri setini oluştur

12. kaydet

In [10]:
import pandas as pd

In [12]:
dataFrame = pd.read_csv("e_ticaret_veri_seti.csv")
# 1. Dosya Okundu

In [20]:
dataFrame.isnull().sum()
# 2. Okunan dosyada sutünların boş olan yerlerinin sayısı ekrana print ettirildi.

siparis_id          0
musteri_id          0
siparis_tarihi      0
sehir              25
bolge               0
kategori            0
urun_adi            0
adet                0
birim_fiyat         0
indirim_orani      16
kargo_ucreti        0
odeme_turu         35
musteri_tipi       42
teslimat_gunu      28
musteri_puani      56
iade_durumu         0
kar_marji_orani     0
toplam_tutar        0
dtype: int64

In [26]:
eksik_sayilari = dataFrame.isnull().sum()
type(eksik_sayilari)

pandas.core.series.Series

In [34]:
eksik_oranlari = 100*(eksik_sayilari / len(dataFrame))
eksik_oranlari

siparis_id         0.000000
musteri_id         0.000000
siparis_tarihi     0.000000
sehir              1.750700
bolge              0.000000
kategori           0.000000
urun_adi           0.000000
adet               0.000000
birim_fiyat        0.000000
indirim_orani      1.120448
kargo_ucreti       0.000000
odeme_turu         2.450980
musteri_tipi       2.941176
teslimat_gunu      1.960784
musteri_puani      3.921569
iade_durumu        0.000000
kar_marji_orani    0.000000
toplam_tutar       0.000000
dtype: float64

In [40]:
eksik_oranlari.round(1)

siparis_id         0.0
musteri_id         0.0
siparis_tarihi     0.0
sehir              1.8
bolge              0.0
kategori           0.0
urun_adi           0.0
adet               0.0
birim_fiyat        0.0
indirim_orani      1.1
kargo_ucreti       0.0
odeme_turu         2.5
musteri_tipi       2.9
teslimat_gunu      2.0
musteri_puani      3.9
iade_durumu        0.0
kar_marji_orani    0.0
toplam_tutar       0.0
dtype: float64

In [58]:
# 4. eksik veri içeren satırları inceleme
# NaN sayısal sutünlardaki boşluk, none nesne türündeki(object) boşluk isnull() ikisinide alır.
eksik_veri_olan_satirlar = dataFrame[dataFrame.isnull().any(axis = 1)]

In [60]:
eksik_veri_olan_satirlar.head()

,siparis_id,musteri_id,siparis_tarihi,sehir,bolge,kategori,urun_adi,adet,birim_fiyat,indirim_orani,kargo_ucreti,odeme_turu,musteri_tipi,teslimat_gunu,musteri_puani,iade_durumu,kar_marji_orani,toplam_tutar
19,SIP100677,MUS1148,2024-07-11 16:24:00,Adana,Akdeniz,Spor,Dambıl Seti,4,1517.65,0.0,29.9,Kapıda Ödeme,Mevcut,3.0,NaN,Hayır,0.311,6100.50
33,SIP101126,MUS1406,2024-09-11 20:05:00,Mersin,Akdeniz,Elektronik,Bluetooth Hoparlör,1,1159.89,0.1,39.9,Kredi Kartı,NaN,2.0,4.0,Hayır,0.204,1083.80
50,SIP101040,MUS1386,2025-04-01 09:30:00,Trabzon,Karadeniz,Spor,Dambıl Seti,1,1554.15,0.0,49.9,Banka Kartı,NaN,4.0,5.0,Hayır,0.217,1604.05
60,SIP100890,MUS1271,2024-11-07 19:47:00,İzmir,Ege,Kitap,Girişimcilik,4,216.38,NaN,49.9,Kredi Kartı,Yeni,1.0,3.0,Hayır,0.199,915.42
61,SIP101317,MUS1060,2024-09-05 20:49:00,NaN,Akdeniz,Ev ve Yaşam,Saklama Kutusu,1,233.63,0.1,29.9,Dijital Cüzdan,Yeni,5.0,2.0,Hayır,0.385,240.17

In [62]:
# 5. Eksik verileri içeren yerleri sil
df_silinen = dataFrame.dropna()
df_silinen.shape

(1239, 18)

In [64]:
df_silinen

,siparis_id,musteri_id,siparis_tarihi,sehir,bolge,kategori,urun_adi,adet,birim_fiyat,indirim_orani,kargo_ucreti,odeme_turu,musteri_tipi,teslimat_gunu,musteri_puani,iade_durumu,kar_marji_orani,toplam_tutar
0,SIP101125,MUS1391,2024-01-13 17:06:00,İstanbul,Marmara,Kozmetik,Nemlendirici,1,414.51,0.05,49.9,Kredi Kartı,Yeni,3.0,5.0,Hayır,0.220,443.68
1,SIP100837,MUS1347,2025-03-17 21:13:00,Gaziantep,Güneydoğu Anadolu,Spor,Dambıl Seti,2,1475.15,0.10,29.9,Banka Kartı,VIP,4.0,1.0,Hayır,0.361,2685.17
2,SIP100050,MUS1066,2025-06-03 12:42:00,Kayseri,İç Anadolu,Kitap,İş Analitiği Rehberi,1,289.02,0.05,29.9,Kredi Kartı,Mevcut,6.0,2.0,Hayır,0.348,304.47
3,SIP100263,MUS1008,2024-08-10 15:13:00,Antalya,Akdeniz,Kitap,Girişimcilik,5,194.78,0.00,49.9,Kapıda Ödeme,Yeni,3.0,5.0,Hayır,0.250,1023.80
4,SIP100707,MUS1291,2024-08-19 08:24:00,Gaziantep,Güneydoğu Anadolu,Elektronik,Powerbank,3,841.80,0.05,39.9,Dijital Cüzdan,Mevcut,4.0,5.0,Hayır,0.280,2439.03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1422,SIP101222,MUS1440,2025-05-14 09:21:00,Bursa,Marmara,Spor,Dambıl Seti,1,1488.18,0.00,29.9,Kredi Kartı,Mevcut,3.0,4.0,Hayır,0.189,1518.08
1423,SIP101093,MUS1187,2024-06-08 20:42:00,İstanbul,Marmara,Spor,Yoga Matı,1,772.23,0.00,29.9,Kredi Kartı,Mevcut,3.0,2.0,Hayır,0.275,802.13
1424,SIP101193,MUS1297,2025-11-06 08:17:00,Gaziantep,Güneydoğu Anadolu,Spor,Suluk,2,187.03,0.00,59.9,Kredi Kartı,Yeni,2.0,4.0,Evet,0.243,433.96
1426,SIP101060,MUS1189,2025-04-19 21:52:00,Kocaeli,Marmara,Kitap,Veri Bilimi 101,2,248.55,0.05,59.9,banka karti,Yeni,4.0,3.0,Hayır,0.373,532.14
1427,SIP100642,MUS1289,2024-09-22 16:36:00,Ankara,İç Anadolu,Kozmetik,Güneş Kremi,1,424.84,0.20,0.0,Dijital Cüzdan,Yeni,2.0,4.0,Hayır,0.317,339.87

In [81]:
# 6. sayısal eksik verileri ortalama
df_ortalama = dataFrame.copy()
sayisal_sutunlar = dataFrame.select_dtypes(include = ["float64","int64"]).columns
for sutun in sayisal_sutunlar:
    df_ortalama[sutun] = df_ortalama[sutun].fillna(df_ortalama[sutun].mean())
df_ortalama[sayisal_sutunlar].isnull().sum()

adet               0
birim_fiyat        0
indirim_orani      0
kargo_ucreti       0
teslimat_gunu      0
musteri_puani      0
kar_marji_orani    0
toplam_tutar       0
dtype: int64

In [85]:
# 7. sayısal eksik verileri median
df_ortalama = dataFrame.copy()
sayisal_sutunlar = df_ortalama.select_dtypes(include=["float64", "int64"]).columns

for sutun in sayisal_sutunlar:
  df_ortalama[sutun] = df_ortalama[sutun].fillna(df_ortalama[sutun].median())
df_ortalama[sayisal_sutunlar].isnull().sum()

adet               0
birim_fiyat        0
indirim_orani      0
kargo_ucreti       0
teslimat_gunu      0
musteri_puani      0
kar_marji_orani    0
toplam_tutar       0
dtype: int64

In [89]:
# 8. sayısal eksik verileri mod
df_mod = dataFrame.copy()
sayisal_sutunlar = df_mod.select_dtypes(include=["float64", "int64"]).columns

for sutun in sayisal_sutunlar:
    en_cok_tekrar_eden = df_mod[sutun].mode()[0]
    df_mod[sutun] = df_mod[sutun].fillna(en_cok_tekrar_eden)
df_ortalama[sayisal_sutunlar].isnull().sum()

adet               0
birim_fiyat        0
indirim_orani      0
kargo_ucreti       0
teslimat_gunu      0
musteri_puani      0
kar_marji_orani    0
toplam_tutar       0
dtype: int64

In [97]:
# 9. kategorik eskik verileri mod ile doldurma
df_mod_kategorik = dataFrame.copy()
kategorik_sutunlar = df_mod_kategorik.select_dtypes(include = ["object"]).columns
for sutun in kategorik_sutunlar:
    df_mod_kategorik[sutun] = df_mod_kategorik[sutun].fillna(df_mod_kategorik[sutun].mode()[0])
df_mod_kategorik[kategorik_sutunlar].isnull().sum()

siparis_id        0
musteri_id        0
siparis_tarihi    0
sehir             0
bolge             0
kategori          0
urun_adi          0
odeme_turu        0
musteri_tipi      0
iade_durumu       0
dtype: int64

In [101]:
# 10. kategorik eksik verileri sabit bir değer ile doldurma
df_sabit_kategorik = dataFrame.copy()
for sutun in kategorik_sutunlar:
    df_sabit_kategorik[sutun] = df_sabit_kategorik[sutun].fillna("bilinmiyor")
df_sabit_kategorik[kategorik_sutunlar].isnull().sum()

siparis_id        0
musteri_id        0
siparis_tarihi    0
sehir             0
bolge             0
kategori          0
urun_adi          0
odeme_turu        0
musteri_tipi      0
iade_durumu       0
dtype: int64

In [103]:
df_guncel = dataFrame.copy()

for sutun in kategorik_sutunlar:
    df_guncel[sutun].fillna(df_guncel[sutun].mode()[0])

for sutun in sayisal_sutunlar:
    df_guncel[sutun].fillna(df_guncel[sutun].median())

In [107]:
df_guncel.to_csv("e_ticaret_veri_seti_eksik_veriler_duzenlendi.csv",index = False, encoding = "utf-8-sig")