# Tekrarlayan ve Tutarsız Kayıtlar
## Amaç:
  1. Veri setindeki tekrarlayan ve tutarsız kayıtları tespit edip temizlemek

## Adımlar:
  1. Veri setini yükle
  2. Tekrarlayan kayıtları tespit et
  3. Tekrarlayan kayıtları incele
  4. Tekrarlayan kayıtları temizle
  5. Tutarsız kategorik değerleri inceleme
  6. Şehir sütunundaki tutarsızlığı giderme
  7. Kategori sütunundaki tutarsızlığı giderme
  8. Ödeme türü sütunundaki tutarsızlığı giderme
  9. Müşteri tipi sütunundaki tutarsızlığı giderme
  10. Mantıksal olarak hatalı kayıtlar incele
  11. Mantıksal olarak hatalı kayıtlar temizle
  12. Kaydet

In [4]:
import pandas as pd

In [39]:
# 1. veri setini yükle
dataFrame = pd.read_csv("e_ticaret_veri_seti_veri_tipleri_duzenlendi.csv")
dataFrame.shape

(1428, 22)

In [18]:
tekrarlayan_kayitlar = dataFrame[dataFrame.duplicated()]
tekrarlayan_kayitlar.shape

(28, 22)

In [29]:
pd.set_option('display.max_columns',None)
tekrarlayan_kayitlar.head()

,siparis_id,musteri_id,siparis_tarihi,sehir,bolge,kategori,urun_adi,adet,birim_fiyat,indirim_orani,kargo_ucreti,odeme_turu,musteri_tipi,teslimat_gunu,musteri_puani,iade_durumu,kar_marji_orani,toplam_tutar,siparis_yili,siparis_ay,siparis_gunu,haftanin_gunu
174,SIP100479,MUS1099,2025-06-10 20:32:00,İstanbul,Marmara,Kozmetik,Güneş Kremi,3,455.19,0.00,49.9,Kredi Kartı,Yeni,1.0,5.0,Hayır,0.200,1415.47,2025,6,10,Tuesday
315,SIP100707,MUS1291,2024-08-19 08:24:00,Gaziantep,Güneydoğu Anadolu,Elektronik,Powerbank,3,841.80,0.05,39.9,Dijital Cüzdan,Mevcut,4.0,5.0,Hayır,0.280,2439.03,2024,8,19,Monday
324,SIP100533,MUS1128,2024-11-19 14:22:00,Trabzon,Karadeniz,Kitap,Python Notları,2,225.82,0.00,39.9,Kredi Kartı,Yeni,4.0,5.0,Hayır,0.234,491.54,2024,11,19,Tuesday
613,SIP100725,MUS1146,2025-05-24 10:10:00,Kocaeli,Marmara,Kitap,Zaman Yönetimi,2,154.18,0.05,49.9,Banka Kartı,Yeni,3.0,5.0,Hayır,0.385,342.84,2025,5,24,Saturday
637,SIP100940,MUS1032,2025-03-25 20:06:00,Samsun,Karadeniz,Kozmetik,Serum,1,507.46,0.15,39.9,Banka Kartı,Mevcut,3.0,4.0,Evet,0.402,471.24,2025,3,25,Tuesday

In [37]:
dataFrame = dataFrame.drop_duplicates()
dataFrame.shape

(1400, 22)

In [47]:
# 5. tutarsız kategorik değerleri incele
dataFrame["sehir"].unique()

array(['İstanbul', 'Gaziantep', 'Kayseri', 'Antalya', 'Konya', 'Ankara',
       'Bursa', 'Trabzon', 'Adana', 'Mersin', 'Kocaeli', 'İzmir',
       'Eskişehir', 'Samsun', nan, 'istanbul', 'ankara', 'Istanbul',
       'gaziantep', 'Izmir'], dtype=object)

In [54]:
dataFrame["kategori"].unique()

array(['Kozmetik', 'Spor', 'Kitap', 'Elektronik', 'Ofis', 'ofis',
       'Ev ve Yaşam', 'Elektronik ', 'spor', 'kozmetık', 'ev ve yaşam',
       'kitap', 'Kozmetik ', 'elektronik', 'Ev&Yaşam'], dtype=object)

In [52]:
dataFrame["odeme_turu"].unique()

array(['Kredi Kartı', 'Banka Kartı', 'Kapıda Ödeme', 'Dijital Cüzdan',
       'Havale/EFT', nan, 'Kart', 'kredi kartı', 'dijital cüzdan', 'eft',
       'banka karti', 'Kapida Odeme', 'Havale'], dtype=object)

In [56]:
dataFrame["musteri_tipi"].unique()

array(['Yeni', 'VIP', 'Mevcut', nan, 'yeni', 'Vip', 'mevcut', 'vip'],
      dtype=object)

In [58]:
def metin_normalize_et(series):
    return (
        series.astype(str)
        .str.strip()
        .str.lower()
        .str.replace("i̇", "i", regex=False)
        .str.replace("ı", "i", regex=False)
        .str.replace("ö", "o", regex=False)
        .str.replace("ü", "u", regex=False)
        .str.replace("ç", "c", regex=False)
        .str.replace("ş", "s", regex=False)
        .str.replace("ğ", "g", regex=False)
    )

In [60]:
dataFrame["sehir"] = metin_normalize_et(dataFrame["sehir"])

In [62]:
dataFrame["sehir"].unique()

array(['istanbul', 'gaziantep', 'kayseri', 'antalya', 'konya', 'ankara',
       'bursa', 'trabzon', 'adana', 'mersin', 'kocaeli', 'izmir',
       'eskisehir', 'samsun', 'nan'], dtype=object)

In [64]:
sehir_duzeltme_haritasi = {
    "istanbul": "İstanbul",
    "ankara": "Ankara",
    "izmir": "İzmir",
    "antalya": "Antalya",
    "konya": "Konya",
    "bursa": "Bursa",
    "adana": "Adana",
    "gaziantep": "Gaziantep",
    "mersin": "Mersin",
    "kayseri": "Kayseri",
    "eskisehir": "Eskişehir",
    "samsun": "Samsun",
    "trabzon": "Trabzon",
    "kocaeli": "Kocaeli"
}

In [70]:
dataFrame["sehir"] = dataFrame["sehir"].replace(sehir_duzeltme_haritasi)
dataFrame["sehir"].unique()

array(['İstanbul', 'Gaziantep', 'Kayseri', 'Antalya', 'Konya', 'Ankara',
       'Bursa', 'Trabzon', 'Adana', 'Mersin', 'Kocaeli', 'İzmir',
       'Eskişehir', 'Samsun', 'nan'], dtype=object)

In [72]:
dataFrame["sehir"].value_counts()

sehir
İstanbul     309
Ankara       171
İzmir        158
Antalya      108
Konya         88
Bursa         88
Adana         78
Gaziantep     69
Samsun        59
Kayseri       58
Mersin        57
Eskişehir     57
Trabzon       56
Kocaeli       47
nan           25
Name: count, dtype: int64

In [74]:
dataFrame["kategori"] = metin_normalize_et(dataFrame["kategori"])

In [82]:
kategori_duzeltme_haritasi = {
    "elektronik": "Elektronik",
    "kitap": "Kitap",
    "kozmetik": "Kozmetik",
    "kozmetık": "Kozmetik",
    "spor": "Spor",
    "ev yasam": "Ev Yaşam",
    "ev ve yasam": "Ev Yaşam",
    "ev&yasam": "Ev Yaşam",
    "ofis": "Ofis"
}
dataFrame["kategori"] = dataFrame["kategori"].replace(kategori_duzeltme_haritasi)
print("\nKategori sütunu düzeltildikten sonraki frekanslar:")
dataFrame["kategori"].value_counts()

Kategori sütunu düzeltildikten sonraki frekanslar:

kategori
Kitap         259
Elektronik    248
Spor          240
Ofis          234
Kozmetik      228
Ev Yaşam      219
Name: count, dtype: int64

In [84]:
dataFrame["odeme_turu"] = metin_normalize_et(dataFrame["odeme_turu"])
odeme_turu_duzeltme_haritasi = {
    "kredi karti": "Kredi Kartı",
    "kart": "Kredi Kartı",
    "banka karti": "Banka Kartı",
    "dijital cuzdan": "Dijital Cüzdan",
    "kapida odeme": "Kapıda Ödeme",
    "havale": "Havale/EFT",
    "eft": "Havale/EFT",
    "havale/eft": "Havale/EFT"
}
dataFrame["odeme_turu"] = dataFrame["odeme_turu"].replace(odeme_turu_duzeltme_haritasi)

In [92]:
print("\nÖdeme türü sütunu düzeltildikten sonraki frekanslar:")
dataFrame["odeme_turu"].value_counts()

Ödeme türü sütunu düzeltildikten sonraki frekanslar:

odeme_turu
Kredi Kartı       709
Banka Kartı       230
Dijital Cüzdan    203
Havale/EFT        149
Kapıda Ödeme      102
nan                35
Name: count, dtype: int64

In [102]:
dataFrame["musteri_tipi"] = metin_normalize_et(dataFrame["musteri_tipi"])

musteri_tipi_duzeltme_haritasi = {
    "mevcut": "Mevcut",
    "yeni": "Yeni",
    "vip": "VIP"
}

dataFrame["musteri_tipi"] = dataFrame["musteri_tipi"].replace(musteri_tipi_duzeltme_haritasi)

print("\nMüşteri tipi sütunu düzeltildikten sonraki frekanslar:")
print(dataFrame["musteri_tipi"].value_counts())

Müşteri tipi sütunu düzeltildikten sonraki frekanslar:
musteri_tipi
Mevcut    690
Yeni      529
VIP       167
nan        42
Name: count, dtype: int64

In [141]:
# =========================================================
# 10. Adım: Mantıksal olarak hatalı kayıtları inceleyelim
# Negatif ya da anlamsız değerler bazı kayıtlarda veri kalitesi problemi oluşturabilir.
# =========================================================

hatali_kayitlar = dataFrame[
    (dataFrame["adet"] <= 0) |
    (dataFrame["birim_fiyat"] <= 0) |
    (dataFrame["toplam_tutar"] <= 0) |
    (dataFrame["teslimat_gunu"] < 0) |
    (dataFrame["musteri_puani"] < 0) |
    (dataFrame["musteri_puani"] > 5)
]

In [143]:
type(hatali_kayitlar)

pandas.core.frame.DataFrame

In [145]:
hatali_kayitlar

,siparis_id,musteri_id,siparis_tarihi,sehir,bolge,kategori,urun_adi,adet,birim_fiyat,indirim_orani,kargo_ucreti,odeme_turu,musteri_tipi,teslimat_gunu,musteri_puani,iade_durumu,kar_marji_orani,toplam_tutar,siparis_yili,siparis_ay,siparis_gunu,haftanin_gunu
609,SIP100095,MUS1165,2025-10-12 21:31:00,İstanbul,Marmara,Kozmetik,Şampuan,2,190.17,0.10,0.0,Dijital Cüzdan,Mevcut,3.0,6.0,Hayır,0.416,342.31,2025,10,12,Sunday
1008,SIP101290,MUS1225,2024-01-16 21:46:00,Kocaeli,Marmara,Kozmetik,Yüz Temizleme Jeli,2,303.82,0.05,29.9,Kredi Kartı,Yeni,5.0,7.0,Evet,0.287,607.16,2024,1,16,Tuesday

In [147]:
dataFrame = dataFrame[
    (dataFrame["adet"] > 0) &
    (dataFrame["birim_fiyat"] > 0) &
    (dataFrame["toplam_tutar"] > 0) &
    (dataFrame["teslimat_gunu"] >= 0) &
    (dataFrame["musteri_puani"] >= 0) &
    (dataFrame["musteri_puani"] <= 5)
]

In [149]:
dataFrame.shape

(1342, 22)

In [151]:
dataFrame.to_csv("e_ticaret_veri_seti_tekrarlayan_kayitlar_duzenlendi.csv",index = False, encoding = "utf-8-sig")