# Grup Bazlı Analiz
## Amaç:
  1. Veri setini farklı kırılımlara ayırarak grup bazlı analiz yapma

## Adımlar:
  1. Veri seti yüklemek
  2. Sütunları belirleme
  3. Kategoriye göre temel analiz
  4. Şehre  göre temel analiz
  5. Müşteri tipine göre temel analiz
  6. Ödeme türüne göre temel analiz
  7. Birden fazla sütun ile grup bazlı analiz

In [2]:
import pandas as pd

In [4]:
df = pd.read_csv("e_ticaret_veri_seti_aykiri_degerler_duzenlendi.csv")

In [6]:
df.shape

(1186, 22)

In [8]:
grup_sutunlari = ["kategori","sehir","musteri_tipi","odeme_turu"]
sayisal_analiz_sutunlari = ["birim_fiyat","toplam_tutar","teslimat_gunu","musteri_puani"]

In [10]:
# 3. Kategoriye göre temel analiz
kategori_analizi = df.groupby("kategori").agg(
    {
        "toplam_tutar" : ["count","mean","sum"],
        "birim_fiyat": "mean",
        "musteri_puani":"mean",
        "teslimat_gunu":"median"
    }
).round(2)
kategori_analizi

           toplam_tutar                     birim_fiyat musteri_puani  \
                  count     mean        sum        mean          mean
kategori
Elektronik          157  1548.31  243084.26     1080.20          3.97
Ev Yaşam            202   750.52  151605.73      353.19          3.87
Kitap               239   495.56  118439.83      224.70          3.99
Kozmetik            212   755.78  160225.69      374.11          4.13
Ofis                170   301.49   51252.50      141.03          3.94
Spor                206  1040.64  214372.56      636.31          3.96

           teslimat_gunu
                  median
kategori
Elektronik           3.0
Ev Yaşam             3.0
Kitap                4.0
Kozmetik             3.0
Ofis                 3.0
Spor                 3.0

In [12]:
# 4. şehre göre temel analiz
sehir_analizi = df.groupby("sehir").agg(
    {
        "toplam_tutar" : ["count","mean","sum"],
        "birim_fiyat": "mean",
        "musteri_puani":"mean",
        "teslimat_gunu":"median"
    }
).round(2)
sehir_analizi

          toplam_tutar                    birim_fiyat musteri_puani  \
                 count    mean        sum        mean          mean
sehir
Adana               70  790.51   55335.90      430.16          4.11
Ankara             143  756.81  108223.70      459.43          3.75
Antalya             86  790.51   67983.65      385.13          4.05
Bursa               70  713.86   49970.06      353.57          3.97
Eskişehir           46  833.03   38319.49      476.89          4.04
Gaziantep           56  903.35   50587.64      533.26          4.05
Kayseri             45  688.83   30997.47      390.88          3.80
Kocaeli             40  680.96   27238.26      313.69          3.45
Konya               78  804.10   62719.85      527.94          4.24
Mersin              46  804.19   36992.94      429.19          4.07
Samsun              48  812.08   38979.69      419.14          4.10
Trabzon             51  750.35   38267.90      460.19          3.82
İstanbul           256  864.18  221231.23      471.95          4.13
İzmir              130  745.90   96967.10      441.19          3.82

          teslimat_gunu
                 median
sehir
Adana               3.0
Ankara              3.0
Antalya             3.0
Bursa               3.5
Eskişehir           3.0
Gaziantep           4.0
Kayseri             3.0
Kocaeli             3.0
Konya               3.0
Mersin              3.0
Samsun              3.0
Trabzon             3.0
İstanbul            3.0
İzmir               3.0

In [14]:
# 7. Birden fazla sütun ile veri analizi
kategori_musteri_analizi = df.groupby(["kategori","musteri_tipi"]).agg(
    {
      "toplam_tutar": ["count", "mean", "sum"],
      "birim_fiyat": "mean",
      "musteri_puani": "mean",
      "teslimat_gunu": "median"
    }
).round(1)
kategori_musteri_analizi

                        toplam_tutar                   birim_fiyat  \
                               count    mean       sum        mean
kategori   musteri_tipi
Elektronik Mevcut                 82  1639.9  134472.8      1080.6
           VIP                    22  1370.6   30153.5       963.9
           Yeni                   46  1524.0   70102.2      1133.3
Ev Yaşam   Mevcut                101   777.9   78565.8       367.4
           VIP                    24   791.3   18991.2       337.4
           Yeni                   76   693.6   52714.3       337.7
Kitap      Mevcut                116   477.4   55373.2       224.6
           VIP                    25   564.9   14123.0       230.0
           Yeni                   91   498.9   45400.7       223.4
Kozmetik   Mevcut                110   729.7   80267.8       372.4
           VIP                    30   735.9   22076.3       368.2
           Yeni                   65   806.3   52412.0       374.0
Ofis       Mevcut                 72   292.4   21051.9       140.9
           VIP                    18   303.8    5467.9       142.3
           Yeni                   77   313.8   24161.7       141.5
Spor       Mevcut                 90  1014.0   91258.2       612.4
           VIP                    18  1278.2   23007.0       902.0
           Yeni                   90  1013.8   91245.3       594.0

                        musteri_puani teslimat_gunu
                                 mean        median
kategori   musteri_tipi
Elektronik Mevcut                 4.0           3.0
           VIP                    3.9           2.0
           Yeni                   4.0           3.0
Ev Yaşam   Mevcut                 3.9           3.0
           VIP                    3.9           3.5
           Yeni                   3.8           3.0
Kitap      Mevcut                 4.0           4.0
           VIP                    3.9           4.0
           Yeni                   4.0           3.0
Kozmetik   Mevcut                 4.0           3.0
           VIP                    4.2           4.0
           Yeni                   4.2           3.0
Ofis       Mevcut                 4.0           3.0
           VIP                    3.4           2.5
           Yeni                   4.0           3.0
Spor       Mevcut                 4.0           3.0
           VIP                    4.1           3.0
           Yeni                   3.9           3.0