# Pivot Tablolar ile Analiz

## Amaç:
  1. Veri setini iki yönlü kırılımlar ile özetleyecek bir pivot tablo oluşturalım

## Adımlar:
  1. Veri setini yükleme
  2. Pivot tablo için kullanılacak sütunların belirlenmesi
  3. Kategori ve müşteri tipine göre pivot tablo oluşturma
  4. Şehir ve ödeme türüne göre pivot tablo oluşturma
  5. Kategori ve ödeme türüne göre ortalama sipari tutarını inceleme
  6. Şehir ve müşteri tipine göre sipariş sayılarını inceleme

In [3]:
import pandas as pd

In [5]:
df = pd.read_csv("e_ticaret_veri_seti_aykiri_degerler_duzenlendi.csv")
df.shape

(1186, 22)

In [7]:
# 2. Pivot tablo için kullanılacak sütunları belirle
pivot_satir_sutunlari = ["kategori","sehir"],
pivot_sutun_sutunlari = ["musteri_tipi","odeme_turu"]
deger_sutunlari = ["toplam_tutar","birim_fiyat"]

In [9]:
# 3. Şehir ve ödeme türüne göre pivot tablo oluşturalım
pivot_kategori_musteri = pd.pivot_table(
    df,
    index = "sehir",
    columns = "odeme_turu",
    values = "toplam_tutar",
    aggfunc = "sum"
).round(1)
pivot_kategori_musteri

odeme_turu  Banka Kartı  Dijital Cüzdan  Havale/EFT  Kapıda Ödeme  Kredi Kartı
sehir
Adana            9455.7          9134.0      5565.5        5851.8      24218.3
Ankara          16537.0         17848.9     13799.8        6811.2      52943.3
Antalya          9986.8          8061.5      5781.2        5256.1      38205.3
Bursa            5795.8          7424.1      7475.1        4024.1      25251.0
Eskişehir        4507.2          6989.5      2029.2        4013.1      20780.5
Gaziantep        8591.5         10275.6      3746.8        2853.9      24406.4
Kayseri          5155.2          3406.8      6466.2        6119.5       9191.9
Kocaeli          5220.6          7376.3      3373.7        4169.8       7097.8
Konya           16606.9          9379.3      4558.2        2611.8      27839.0
Mersin           9872.2          4307.8      2454.0           NaN      20359.0
Samsun           5934.8          9295.9      4345.8         177.3      18456.1
Trabzon          7006.7          3588.6      6573.0        3298.2      16125.0
İstanbul        46890.9         34714.5     23581.4        5602.9      97839.1
İzmir           12867.0         16499.0      9812.6        7589.3      47387.8

In [15]:
# 4. Kategori ve müşteri tipine göre pivot tablo oluşturalım
pivot_kategori_musteri = pd.pivot_table(
    df,
    index="kategori",
    columns="musteri_tipi",
    values="toplam_tutar",
    aggfunc="mean"
).round(2)

print("\nKategori ve müşteri tipine göre ortalama toplam tutar pivot tablosu:")
pivot_kategori_musteri

Kategori ve müşteri tipine göre ortalama toplam tutar pivot tablosu:

musteri_tipi   Mevcut      VIP     Yeni
kategori
Elektronik    1639.91  1370.62  1523.96
Ev Yaşam       777.88   791.30   693.61
Kitap          477.35   564.92   498.91
Kozmetik       729.71   735.88   806.34
Ofis           292.39   303.77   313.79
Spor          1013.98  1278.16  1013.84